### PR TITLE
Traffic signs

### PR DESCRIPTION
**Pull request by abdelq**
Exported the meshes to `.obj`. *Did not test them yet in the simulator.*
There seems to be a certain degree of repetition (some textures vary just slightly, but their QR code isn't the same).

Related to #26.

### CODE REVIEW

**Comment by maximecb** [comment]
@liampaull Another question I have is: does the numbering of these files matter, is `sign_001` referenced/defined somewhere?

**Comment by abdelq** [comment]
@maximecb Using blender and bash

**Comment by abdelq** [comment]
So I took only the first sign of each type, renamed them using the same names in the tags DB and swapped the "QR code" and the sign position in the `.png`s, since we only see the lower part of the sign most of the time anyway.

I tried to tweak (not a whole rewrite) `objmesh.py` and `graphics.py` to load multiple textures, but to no avail.

**Comment by maximecb** [comment]
I'm planning to do the rewrite in objmesh. I think I have a good solution.

**Comment by maximecb** [comment]
Thank you for taking the time to do this @abdelq :+1:

**Comment by maximecb** [comment]
Multiple texture per model support is in :)

**Pull request merged**
