### PR TITLE
Check Collisions against objects only on drivable tiles

### PR DESCRIPTION
**Pull request by bhairavmehta95**
Small PR that addresses the easier of two issues / optimizations referenced in #24 

Before objects are added to the array with is checked against during collision detection, we make sure atleast one of the vertices of its OBB is on a drivable tile.

### CODE REVIEW

**Comment by maximecb** [comment]
Props for doing it with numpy.

The issue that I see with this approach, however, is that it is possible for an object to be, say, at the corner of multiple tiles, and to partially overlap with a drivable tile, without any of its corners being on it. To accurately solve this problem, I think you might need an OBB test.

**Comment by bhairavmehta95** [comment]
Lot of edge cases w. this problem, but I think this solves it.

**Comment by maximecb** [comment]
I feel like that's a lot of code to add into the `_load_map()` method. Maybe you could factor out more of the generation of possible tiles and corners into a function that goes in collision.py?

**Comment by maximecb** [comment]
Also: 
- I'm getting 6 3 for udem1, but this map shouldn't have any collidable objects.
- The --draw-bbox option for manual_control.py no longer works.

**Comment by bhairavmehta95** [comment]
When I checked the 6,3 and what objects were being added, it's only the signs on udem1 which are all (slightly) on drivable tiles, and you can actually run into them.

Fixed draw-bbox, and I tried to move as much code as I could out of that function, but because it uses some class methods I kept some code there. Let me know if this is okay.

**Pull request merged**
