### PR TITLE
Collisions

### PR DESCRIPTION
**Pull request by bhairavmehta95**
* Adding a multithreaded version of collision detection
* Adding a multithread version of spawning / finding a valid location; also added an inconvenient spawn function (helps with the issue of a spawn point being extremely close to but not intersecting with an object)
* Made collision detection entirely based on numpy matrix multiplication (hopefully to speed things up)
* Added constant `MIN_SPAWN_OBJ_DIST = 0.10`

If this is still too slow, we can still continue to multithread some things (i.e rotating points)

As I open this PR, two notes:

1. Looking for feedback on anything (style, functionality, etc)
2. It will not be able to merge automatically, which I will fix

### CODE REVIEW

**Comment by bhairavmehta95** [comment]
Thanks for the feedback. I will work on this all today

**Comment by bhairavmehta95** [comment]
- [x] ThreadPool - Great suggestion to numpy-ify the code, went from ~5ms to ~ .5ms for checking for collisions! 
- [x] self._collision() inside _valid_pose - Done
- [x] inconvenient_spawn, I feel like it would be best if this took into account the size of objects - Done
- [x] _spawn_helper - Removed threadPools, so no longer need this
- [x] Comments - Done (as well as possible w/out bogging down code). For collisions, maybe it's better to put this into a markdown in `docs/`

Last one: 
- [ ] "duckie_boundbox, it should ideally take into account that the position value is not actually at the center of the duckie."  -- Didn't understand this at all; if that's not the center, what is `cur_pos`? And what point would we want to rotate around? Empirically, rotating around `cur_pos` seems to work fine, but I'd like to fix it.

**Comment by maximecb** [comment]
Looking very good! :)

This is what I expected wrt numpy. Numpy is written in C (or even assembly) and can run a very large amount of computation very fast. However, any computation we have to do in Python is horribly slow in comparison (100-1000x slower). Most of the performance impact right now is probably not even the numpy code itself, but the Python interpreter calling into the numpy code.

The cur_pos is exactly between the wheels. It's at the center of rotation. However, the robot stretches a little bit farther behind this position than it does in the forward direction. The CAMERA_FORWARD_DIST is how much it stretches forward.

**Comment by maximecb** [comment]
Seems ready to merge. I will want until Tuesday to merge, because I want to have time to try it after I merge it.

**Comment by maximecb** [comment]
I pushed a fix for the issue that was causing the tests to fail on maps with no objects, along with some cosmetic changes.

One last fix, if you don't mind:

I feel like the way `_actual_center`  and `duckie_boundbox` work is kind of iffy. I think that `_actual_center` should use `get_dir_vec` to compute the center position directly, not just add to the z component of `cur_pos`. 

I also think that `duckie_boundbox` could take just the actual center, direction vector and right vectors as input. It doesn't need to use `rotate_point`. It would be cleaner and more readable that way IMO.

**Comment by bhairavmehta95** [comment]
Okay, that sounds good. Will take care of that.

Best,
Bhairav

**Pull request merged**
