### PR TITLE
Imitation learning baseline using simulation

### PR DESCRIPTION
**Pull request by mostafaelaraby**
@bhairavmehta95

### CODE REVIEW

**Comment by bhairavmehta95** [comment]
Can we move this into a different folder? i.e, now `learning/` would look like:

```
learning/ 
	imitation/
		basic/ # the old implementation
		improved/ 
			.. your code ..
			approach.md - A file that describes the approach that you're using
```

ideally, you pick a better name than just `improved/`. You can put the original one into `basic/` though.

**Comment by bhairavmehta95** [comment]
ah oops the diffs weren't showing correctly.

It looks good to me except:

- [ ] `pytorch-v2` -> some better name
- [ ] add `approach.md`

**Comment by mostafaelaraby** [comment]
> ah oops the diffs weren't showing correctly.
> 
> It looks good to me except:
> 
> * [ ]  `pytorch-v2` -> some better name
> * [ ]  add `approach.md`

Added README.md in the folder to make ti shown when viewed it contains the approach and a quick start
the parent folder name changed to iil-dagger and the other folder renamed to basic

**Comment by bhairavmehta95** [comment]
really nice work!

**Pull request merged**
