### PR TITLE
new wrapper

### PR DESCRIPTION
**Pull request by nithin127**
to resize images as 80x80

### CODE REVIEW

**Comment by maximecb** [comment]
This is a good idea, but there are two things I would do differently:

- Put the `import cv2` into the function that needs it. This is because OpenCV has been problematic to install on some systems, and I would rather make it so only people who need to use that functionality need to have it installed.

- Don't try to also combine the PyTorch observation reshaping into this wrapper. Keep them separate. If people need to both resize and transpose the observations, they should use both wrappers.

**Comment by nithin127** [comment]
So, `import cv2` would be called every time the `env.reset()` or `env.step()` is called; should I go ahead with this?

**Comment by maximecb** [comment]
Yes, put the import inside both reset and step.

**Comment by maximecb** [comment]
Don't add the `RewardWrapper` to the repo. It's clearly specific to your own use-case/experiments.

**Comment by bhairavmehta95** [comment]
Why not just use the Pytorch transforms for this?

**Comment by bhairavmehta95** [comment]
```python
resize = T.Compose([T.ToPILImage(),
                    T.Resize(40, interpolation=Image.CUBIC),
                    T.ToTensor()])
``` 

https://pytorch.org/tutorials/intermediate/reinforcement_q_learning.html

(You'd put 80 instead of 40)

Also, looking through this, only axes 0 and 2 are swapped, which would make your image, CxWxH instead of CxHxW, no?

https://pytorch.org/docs/stable/torchvision/transforms.html#torchvision.transforms.ToPILImage

**Comment by nithin127** [comment]
@bhairavmehta95 
Florian suggested that we try 80;
And I swap(0,2) just to resize it, then I swap it back -- (0,2) again; so essentially the Resize wrapper is not changing any dimensions

But the PyTorchObsWrapper does use an observation.transpose(2, 1, 0); do you think it should be observation.transpose(2, 0, 1)

**Comment by bhairavmehta95** [comment]
Yeah dimensions don't matter, so I think he's right.

I don't think it matters, as long as it's consistent. Only reason I'd say `2, 0, 1` is then you're only moving the channel. Makes it better to visualize, otherwise, if you feed your image tensor into something like `tensorboardX`, it will show up rotated. (As it's expecting `2, 0, 1`, but you're giving it `2, 1, 0`)

**Comment by nithin127** [comment]
done!

**Comment by maximecb** [comment]
The new wrapper is fine, but you've made a one-line change to the PyTorchObsWrapper. Can you remove that?

**Pull request closed without merging**
