### PR TITLE
Add fix for free_camera.py

### PR DESCRIPTION
**Pull request by CourchesneA**
Added fix to make the script free_camera.py to be coherent with the move of the gym_duckietown folder in src/gym_duckietown.

The import in src/gym_duckietown/envs/__init__.py had to be made relative, (not sure why they were absolute, they were not resolved properly)

### CODE REVIEW

**Comment by CourchesneA** [comment]
Seems like the tests are also using absolute imports. From my understanding of the imports, what we have right now (since we changed the directory structure in [this commit](https://github.com/duckietown/gym-duckietown/commit/d7daaedc8154945f1b712e656cd5eaf448f7fd51), import the gym_duckietown that is installed through pip and does not actually test local changes, which would be completely wrong. (Before the refactor in that commit, gym_duckietown was a local directory so I assume it was reolving it locally and it was fine)

**Comment by AndreaCensi** [comment]
Definitely not the answer.

The good solution is to make this and the others proper CLI executable using the 
entry_points/console_scripts mechanism in setup.py.

**Comment by AndreaCensi** [comment]
If you have to do this, likely you did not run "python setup.py develop" or equivalent command.

**Comment by CourchesneA** [comment]
Awesome, was not aware of this. I'll do the required changes, thanks !

**Pull request merged**
