### PR TITLE
Update Docker instructions

### PR DESCRIPTION
**Pull request by breandan**

### CODE REVIEW

**Comment by breandan** [comment]
@maximecb We should set up an auto-builder on the [Duckietown Docker Hub](https://hub.docker.com/r/duckietown/) and/or [your Docker Hub](https://hub.docker.com/r/maximecb/gym-duckietown/) repository. Either you can do this or I can, with admin access on GitHub.

**Comment by maximecb** [comment]
Could you combine the multiple sub-subsections in Usage/Docker into one?

**Comment by maximecb** [comment]
The docker hub link is currently not working. Is that expected? Also, I think it would be good to include the `docker pull` command as well, for people who are complete newbies.

**Comment by breandan** [comment]
**Re: Readme**, Done. 

**Re: DH auto-builds**, I personally will need admin access to this GitHub repo to make this happen. Alternatively, one of the Duckietown GitHub organization admins can do so.

**Comment by maximecb** [comment]
Thanks Breandan.

I can't give you admin access to this repo because I don't have it myself. Will need to wait for Andrea.

**Pull request merged**
