### PR TITLE
Improvements

### PR DESCRIPTION
**Pull request by gibernas**
Added features:

- randomization of camera using CarnivalMirror with --camera_rand
- randomization of dynamics of the Duckiebot using the --dynamics_rand arg
- removed unused code in dynamics
- cleanup

### CODE REVIEW

**Comment by bhairavmehta95** [comment]
Where did you get the camera calibration from?

**Comment by bhairavmehta95** [comment]
Do you happen to have an image of what this looks like with the calibration you've used? I've been trying to doing this with `cv2.fisheye` but no luck at all, so mostly just curious

**Comment by gibernas** [comment]
What do you mean? The nominal camera parameters is the same as it was before, but now we can sample around it. We probably should a better one though.

**Comment by liampaull** [comment]
how can I test this?

**Comment by gibernas** [comment]
You can run the simulator with `--dynamics_rand` for randomizing the wheel calibration, or `--camera_rand` (only available if `distortion is used`), which randomizes the camera parameters.

**Comment by liampaull** [comment]
@gibernas can we merge this?

**Comment by bhairavmehta95** [comment]
Have we checked that the default values getting perturbed like this still generate reasonable values? i.e when I wrote the original camera distortion stuff, minor changes to the extrinsic matrix really mess up various things.. it's not super intuitive, but as long as its been checked this looks good to me.

**Comment by liampaull** [comment]
the failing test looks suspicious

**Comment by AndreaCensi** [comment]
@liampaull the `daffy` branch itself is failing:  

https://circleci.com/gh/duckietown/gym-duckietown/tree/daffy

will fix

**Comment by AndreaCensi** [comment]
@gibernas because this PR is from a fork I cannot make modifications.
Can you merge daffy?

**Comment by gibernas** [comment]
@AndreaCensi done

**Comment by AndreaCensi** [comment]
@bhairavmehta95 should we merge? 
There are not tests anyway for what you mention.

**Comment by AndreaCensi** [comment]
guys let's merge and see how it goes

**Comment by bhairavmehta95** [comment]
Sure sorry it was more of a curiosity question. Let's merge 🤞

**Pull request merged**
