### PR TITLE
Fullyobs nav

### PR DESCRIPTION
**Pull request by bhairavmehta95**
Enables top down rendering **only for the HUMAN** with `env.render(mode='top_down')`

Addresses #101

### CODE REVIEW

**Comment by bhairavmehta95** [comment]
This will need to be merged after #100. 

@AndreaCensi this is the top down mode you were asking for by the way. I unfortunately forked this branch from the branch where I had all of the changes for dynamic duckiebots, but the two should be merged into master within a few hours / after some reviews.

**Comment by AndreaCensi** [comment]
@bhairavmehta95 thanks - I merged the other one.

**Comment by AndreaCensi** [comment]
@bhairavmehta95 I am unsure about the conflicts - can you take a look?

Also, is it possible to have both images generated?
If so, we can produce the two videos at the same time.

**Comment by bhairavmehta95** [comment]
Sure I'll fix the conflicts. And yeah I can do that.

@maximecb can you show me how you got your other simulator to do PiP (agent view and the bigger view?)

**Comment by bhairavmehta95** [comment]
I'll merge this for now, leave the Picture-in-picture views for a different PR / set of issues, since it has to do with the overarching theme of "Rendering", so it might be time to rethink it altogether (i.e Hierarchy of renderers as previously suggested in #84)

**Pull request merged**
