### PR TITLE
Python 2 compatibility

### PR DESCRIPTION
**Pull request by AndreaCensi**

### CODE REVIEW

**Comment by AndreaCensi** [comment]
@breandan I am not sure how to deal with the "ci/dockercloud" tests. There are no logs or anything.

**Comment by AndreaCensi** [comment]
@liampaull ready to merge

**Comment by bhairavmehta95** [comment]
These changes have broken the scripts that people use to try the simulator. We need to make sure that we at least try to move around with `./manual_control.py` and `./free_camera.py`, because those either didn't compile (due to the added dependency on `torch`), and something in these changes has broken the way that those scripts interacted with the environment.

The CircleCI are set up to basically check if the code compiles, and some test actions can be run, but the only way to check keyboard control is to actually run the code ourselves.

**Comment by liampaull** [comment]
@bhairavmehta95 should we revert ?

**Comment by bhairavmehta95** [comment]
No we fixed it in the other PR

**Pull request merged**
