### PR TITLE
Exposing full state; refactoring; various extensions.

### PR DESCRIPTION
**Pull request by AndreaCensi**

### CODE REVIEW

**Comment by AndreaCensi** [comment]
@liampaull can we merge this? need to do further development

**Comment by liampaull** [comment]
I'm really not the right one to ask for this repo. I suggest @bhairavmehta95 or @maximecb or @breandan or @fgolemo

**Comment by bhairavmehta95** [comment]
Sure I will take a look at in when I get in

**Comment by bhairavmehta95** [comment]
Looks okay to me.

**Pull request merged**
