### PR TITLE
Smooth Reward Function / Safe Driving

### PR DESCRIPTION
**Pull request by bhairavmehta95**
Implements a simple safe driving penalty for use for collision detection. (Implemented as described in #24).

We will almost definitely need to scale the rewards from this and the rest of the environment to get the behavior that we are looking for.

### CODE REVIEW

**Comment by bhairavmehta95** [comment]
Will fix the failing test tomorrow.

**Comment by maximecb** [comment]
Just two nitpicks:
- Can you use a more descriptive name for `DUCKIE_SR` and other constants. Also note that I've been referring to the duckiebot elsewhere in the code as robot or agent
- The statement after if or else should go on a separate line.

**Comment by bhairavmehta95** [comment]
Fixed. 

Also, it may be beneficial to merge #32 first, and then this one if that's okay?

Just because there were fixes to things like `draw-bbox` on that PR. 
In the future, I will try to branch out fixes like that (i.e ones that break certain functionality) and merge them into master as soon as possible. Sorry for the inconvenience.

**Comment by maximecb** [comment]
Apologies, I seem to have created more conflicts.

**Comment by maximecb** [comment]
I had removed the pos argument from `_actual_center()`, and made the agent corners local variables in the collision check function.

**Comment by bhairavmehta95** [comment]
Should be fixed now, as long as the tests pass.

**Comment by bhairavmehta95** [comment]
Oh my bad! I got confused when cleaning the merge conflicts so I must have
switched the wrong code.

Will fix asap

**Pull request merged**
